# Generated by Django 5.1.4 on 2024-12-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your own avatar or leave blank to use generated avatar', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Used for avatar generation if no custom avatar is uploaded', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='use_custom_avatar',
            field=models.BooleanField(default=False, help_text='True if user uploaded their own avatar'),
        ),
    ]
